### PR TITLE
Ignore missing languages and force plain-text.

### PR DESCRIPTION
**Pull request by vhf**
Hey! I'm not sure that's the best way of fixing the issue demoed here: https://github.com/vhf/remark-rehype-highlight-issue

This PR is just a suggestion, please tell me what you think!

### CODE REVIEW

**Comment by wooorm** [comment]
Would it make sense, in your case of plain text, to instead add support for `option.plainText` which can be set to an array, and then add a check [here](https://github.com/rehypejs/rehype-highlight/blob/a1b90eccfba0fa38c943084e88082603cdb63f3c/index.js#L38) to ignore those?

**Comment by vhf** [comment]
It wouldn't solve the issue we have. `text` is just an example, ignoring this "language" would still make any unknown language crash `rehype-highlight`.

In my opinion any syntax highlighter should default to not doing anything when it doesn't know about a particular language/syntax. For instance:

    ```foobar
    hello true 0 ()
    ```

should be rendered as: (this is what github renders)

```foobar
hello true 0 ()
```

Currently `rehype-highlight` throws an exception in such cases.

**Comment by wooorm** [comment]
That may be true as well, I personally like to know when I made a typo though, when I’m working on a website and it doesn’t highlight!

How about `options.ignoreMissing` (default: `false`, `true` to swallow errors)?

**Comment by wooorm** [comment]
That’s also why I came up with `plainText` above, as I like to know about typo’s, but use code for plain text as well.

But I guess it could be named `ignore` too, receiving either an array of flags to ignore, or the magic string `'unknown'` to swallow all unknown flags?

**Comment by vhf** [comment]
I like the idea of having a `plainText` language *and* an `ignore` list/flag to ignore any unknown language. 👍 

I might implement these later. I'm still hesitating between `highlight` and `prism`. I'll go with the one for which having numbered lines is the easiest.

**Comment by wooorm** [comment]
Good!

The last part sounds like a separate issue, allowing people to use lowlight, or refractor, or something else [here](https://github.com/rehypejs/rehype-highlight/blob/a1b90eccfba0fa38c943084e88082603cdb63f3c/index.js#L50-L53)?

**Comment by vhf** [comment]
@wooorm Implemented your suggestion, tested, documented.

**Comment by wooorm** [comment]
Done! I changed the try/catch to be a [bit more specific](https://github.com/rehypejs/rehype-highlight/blob/6b983d5ea7c551357c1d0e85168bbc9b4625f82c/index.js#L52-L68), and reworded some stuff.

Thanks for working on this Victor!

**Pull request closed without merging**
