### PR TITLE
Add a way to configure custom languages

### PR DESCRIPTION
**Pull request by artragis**
Hi,

Using rehype-highlight I faced this need : adding a custom language to
the parsable ones.

Highlight allows us to do such a thing, so I added a setting to rehype-highlight to
perform this configuration.

### CODE REVIEW

**Comment by wooorm** [comment]
@artragis Is what you want really custom languages, or is it adding new aliases (like `latex` to `tex`)?
If the latter, maybe we can create simpler other functionality to do that?

**Comment by wooorm** [comment]
Syntaxes are [compiled](https://github.com/wooorm/lowlight/blob/ac8fc15daec36a24ab377c5d59a4e4e9e20bcaf8/lib/core.js#L117) by lowlight/highlight (they are functions that are called to get a grammar). Aliases are a [map of alias names to language names](https://github.com/wooorm/lowlight/blob/ac8fc15daec36a24ab377c5d59a4e4e9e20bcaf8/lib/core.js#L126-L128), internally.

* So I at least think built-in grammar should not be used as an example of a custom grammar
* I think I prefer using some other mechanism to map extra aliases to names (in lowlight as well)

**Comment by artragis** [comment]
ok, so I will just add an "alias" parameter as it will be enough for my primary needs.

**Comment by wooorm** [comment]
Yeah, currently the alias is found by calling the syntax to find the grammar, and then there’s an `.alias` array on that grammar.

I propose

```js
lowlight.registerAlias(name, alias)
lowlight.registerAlias(aliases)
```

Where `aliases` takes an object mapping `name` to `alias`.
And each `alias` is either a `string` or an `Array.<string>`?

For example, you could pass in:

```js
'markdown', 'mkd'
'markdown', ['mkd', 'markd']
{markdown: 'mkd'}
{markdown: ['mkd', 'markd']}
```

Then we can add a one-liner here in `rehype-highlight` to call that function.

What do you think?

**Comment by artragis** [comment]
I think it's good. I'll do it tomorrow.

**Comment by wooorm** [comment]
Sweet, thanks @artragis!

**Comment by artragis** [comment]
I updated my pr with the new version of lowlight @wooorm

**Pull request closed without merging**
